<template>
  <div
    class="flex justify-between items-center flex-wrap lg:-lg:mx-[7px] -mx-[3.5px] list"
  >
    <div class="flex lg:mb-[14px] mb-[7px]">
      <BoardPiece
        :starter="setStarter(0)"
        :row="0"
        :col="0"
        :pos="0"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
      <BoardPiece
        :starter="setStarter(1)"
        :row="0"
        :col="1"
        :pos="1"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
      <BoardPiece
        :starter="setStarter(2)"
        :row="0"
        :col="2"
        :pos="2"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
      <BoardPiece
        :starter="setStarter(3)"
        :row="0"
        :col="3"
        :pos="3"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="dark"
      />
      <BoardPiece
        :starter="setStarter(4)"
        :row="0"
        :col="4"
        :pos="4"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="dark"
      />
      <BoardPiece
        :starter="setStarter(5)"
        :row="0"
        :col="5"
        :pos="5"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="dark"
      />
      <BoardPiece
        :starter="setStarter(6)"
        :row="0"
        :col="6"
        :pos="6"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
      <BoardPiece
        :starter="setStarter(7)"
        :row="0"
        :col="7"
        :pos="7"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
      <BoardPiece
        :starter="setStarter(8)"
        :row="0"
        :col="8"
        :pos="8"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
    </div>
    <div class="flex lg:mb-[14px] mb-[7px]">
      <BoardPiece
        :starter="setStarter(9)"
        :row="1"
        :col="0"
        :pos="9"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
      <BoardPiece
        :starter="setStarter(10)"
        :row="1"
        :col="1"
        :pos="10"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
      <BoardPiece
        :starter="setStarter(11)"
        :row="1"
        :col="2"
        :pos="11"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
      <BoardPiece
        :starter="setStarter(12)"
        :row="1"
        :col="3"
        :pos="12"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="dark"
      />
      <BoardPiece
        :starter="setStarter(13)"
        :row="1"
        :col="4"
        :pos="13"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="dark"
      />
      <BoardPiece
        :starter="setStarter(14)"
        :row="1"
        :col="5"
        :pos="14"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="dark"
      />
      <BoardPiece
        :starter="setStarter(15)"
        :row="1"
        :col="6"
        :pos="15"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
      <BoardPiece
        :starter="setStarter(16)"
        :row="1"
        :col="7"
        :pos="16"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
      <BoardPiece
        :starter="setStarter(17)"
        :row="1"
        :col="8"
        :pos="17"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
    </div>
    <div class="flex lg:mb-[14px] mb-[7px]">
      <BoardPiece
        :starter="setStarter(18)"
        :row="2"
        :col="0"
        :pos="18"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
      <BoardPiece
        :starter="setStarter(19)"
        :row="2"
        :col="1"
        :pos="19"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
      <BoardPiece
        :starter="setStarter(20)"
        :row="2"
        :col="2"
        :pos="20"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
      <BoardPiece
        :starter="setStarter(21)"
        :row="2"
        :col="3"
        :pos="21"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="dark"
      />
      <BoardPiece
        :starter="setStarter(22)"
        :row="2"
        :col="4"
        :pos="22"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="dark"
      />
      <BoardPiece
        :starter="setStarter(23)"
        :row="2"
        :col="5"
        :pos="23"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="dark"
      />
      <BoardPiece
        :starter="setStarter(24)"
        :row="2"
        :col="6"
        :pos="24"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
      <BoardPiece
        :starter="setStarter(25)"
        :row="2"
        :col="7"
        :pos="25"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
      <BoardPiece
        :starter="setStarter(26)"
        :row="2"
        :col="8"
        :pos="26"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
    </div>
    <div class="flex lg:mb-[14px] mb-[7px]">
      <BoardPiece
        :starter="setStarter(27)"
        :row="3"
        :col="0"
        :pos="27"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="dark"
      />
      <BoardPiece
        :starter="setStarter(28)"
        :row="3"
        :col="1"
        :pos="28"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="dark"
      />
      <BoardPiece
        :starter="setStarter(29)"
        :row="3"
        :col="2"
        :pos="29"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="dark"
      />
      <BoardPiece
        :starter="setStarter(30)"
        :row="3"
        :col="3"
        :pos="30"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
      <BoardPiece
        :starter="setStarter(31)"
        :row="3"
        :col="4"
        :pos="31"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
      <BoardPiece
        :starter="setStarter(32)"
        :row="3"
        :col="5"
        :pos="32"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
      <BoardPiece
        :starter="setStarter(33)"
        :row="3"
        :col="6"
        :pos="33"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="dark"
      />
      <BoardPiece
        :starter="setStarter(34)"
        :row="3"
        :col="7"
        :pos="34"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="dark"
      />
      <BoardPiece
        :starter="setStarter(35)"
        :row="3"
        :col="8"
        :pos="35"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="dark"
      />
    </div>
    <div class="flex lg:mb-[14px] mb-[7px]">
      <BoardPiece
        :starter="setStarter(36)"
        :row="4"
        :col="0"
        :pos="36"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="dark"
      />
      <BoardPiece
        :starter="setStarter(37)"
        :row="4"
        :col="1"
        :pos="37"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="dark"
      />
      <BoardPiece
        :starter="setStarter(38)"
        :row="4"
        :col="2"
        :pos="38"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="dark"
      />
      <BoardPiece
        :starter="setStarter(39)"
        :row="4"
        :col="3"
        :pos="39"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
      <BoardPiece
        :starter="setStarter(40)"
        :row="4"
        :col="4"
        :pos="40"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
      <BoardPiece
        :starter="setStarter(41)"
        :row="4"
        :col="5"
        :pos="41"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
      <BoardPiece
        :starter="setStarter(42)"
        :row="4"
        :col="6"
        :pos="42"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="dark"
      />
      <BoardPiece
        :starter="setStarter(43)"
        :row="4"
        :col="7"
        :pos="43"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="dark"
      />
      <BoardPiece
        :starter="setStarter(44)"
        :row="4"
        :col="8"
        :pos="44"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="dark"
      />
    </div>
    <div class="flex lg:mb-[14px] mb-[7px]">
      <BoardPiece
        :starter="setStarter(45)"
        :row="5"
        :col="0"
        :pos="45"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="dark"
      />
      <BoardPiece
        :starter="setStarter(46)"
        :row="5"
        :col="1"
        :pos="46"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="dark"
      />
      <BoardPiece
        :starter="setStarter(47)"
        :row="5"
        :col="2"
        :pos="47"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="dark"
      />
      <BoardPiece
        :starter="setStarter(48)"
        :row="5"
        :col="3"
        :pos="48"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
      <BoardPiece
        :starter="setStarter(49)"
        :row="5"
        :col="4"
        :pos="49"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
      <BoardPiece
        :starter="setStarter(50)"
        :row="5"
        :col="5"
        :pos="50"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
      <BoardPiece
        :starter="setStarter(51)"
        :row="5"
        :col="6"
        :pos="51"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="dark"
      />
      <BoardPiece
        :starter="setStarter(52)"
        :row="5"
        :col="7"
        :pos="52"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="dark"
      />
      <BoardPiece
        :starter="setStarter(53)"
        :row="5"
        :col="8"
        :pos="53"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="dark"
      />
    </div>
    <div class="flex lg:mb-[14px] mb-[7px]">
      <BoardPiece
        :starter="setStarter(54)"
        :row="6"
        :col="0"
        :pos="54"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
      <BoardPiece
        :starter="setStarter(55)"
        :row="6"
        :col="1"
        :pos="55"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
      <BoardPiece
        :starter="setStarter(56)"
        :row="6"
        :col="2"
        :pos="56"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
      <BoardPiece
        :starter="setStarter(57)"
        :row="6"
        :col="3"
        :pos="57"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="dark"
      />
      <BoardPiece
        :starter="setStarter(58)"
        :row="6"
        :col="4"
        :pos="58"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="dark"
      />
      <BoardPiece
        :starter="setStarter(59)"
        :row="6"
        :col="5"
        :pos="59"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="dark"
      />
      <BoardPiece
        :starter="setStarter(60)"
        :row="6"
        :col="6"
        :pos="60"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
      <BoardPiece
        :starter="setStarter(61)"
        :row="6"
        :col="7"
        :pos="61"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
      <BoardPiece
        :starter="setStarter(62)"
        :row="6"
        :col="8"
        :pos="62"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
    </div>
    <div class="flex lg:mb-[14px] mb-[7px]">
      <BoardPiece
        :starter="setStarter(63)"
        :row="7"
        :col="0"
        :pos="63"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
      <BoardPiece
        :starter="setStarter(64)"
        :row="7"
        :col="1"
        :pos="64"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
      <BoardPiece
        :starter="setStarter(65)"
        :row="7"
        :col="2"
        :pos="65"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
      <BoardPiece
        :starter="setStarter(66)"
        :row="7"
        :col="3"
        :pos="66"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="dark"
      />
      <BoardPiece
        :starter="setStarter(67)"
        :row="7"
        :col="4"
        :pos="67"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="dark"
      />
      <BoardPiece
        :starter="setStarter(68)"
        :row="7"
        :col="5"
        :pos="68"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="dark"
      />
      <BoardPiece
        :starter="setStarter(69)"
        :row="7"
        :col="6"
        :pos="69"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
      <BoardPiece
        :starter="setStarter(70)"
        :row="7"
        :col="7"
        :pos="70"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
      <BoardPiece
        :starter="setStarter(71)"
        :row="7"
        :col="8"
        :pos="71"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
    </div>
    <div class="flex">
      <BoardPiece
        :starter="setStarter(72)"
        :row="8"
        :col="0"
        :pos="72"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
      <BoardPiece
        :starter="setStarter(73)"
        :row="8"
        :col="1"
        :pos="73"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
      <BoardPiece
        :starter="setStarter(74)"
        :row="8"
        :col="2"
        :pos="74"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
      <BoardPiece
        :starter="setStarter(75)"
        :row="8"
        :col="3"
        :pos="75"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="dark"
      />
      <BoardPiece
        :starter="setStarter(76)"
        :row="8"
        :col="4"
        :pos="76"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="dark"
      />
      <BoardPiece
        :starter="setStarter(77)"
        :row="8"
        :col="5"
        :pos="77"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="dark"
      />
      <BoardPiece
        :starter="setStarter(78)"
        :row="8"
        :col="6"
        :pos="78"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
      <BoardPiece
        :starter="setStarter(79)"
        :row="8"
        :col="7"
        :pos="79"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
      <BoardPiece
        :starter="setStarter(80)"
        :row="8"
        :col="8"
        :pos="80"
        :selectedRow="SELECTED_ROW"
        :selectedCol="SELECTED_COL"
        gamePiece="light"
      />
    </div>
  </div>
</template>

<script setup>
import { useGameStore } from '@/stores/game';
import BoardPiece from '../components/BoardPiece.vue';
import { storeToRefs } from 'pinia';

const store = useGameStore();
const { SELECTED_COL, SELECTED_ROW } = storeToRefs(store);

const setStarter = (num) => {
  return store.STARTER_PIECES[num] !== '';
};
</script>

<style lang="scss" scoped></style>
